
[blockchain_a]
  type = "anvil"
  docker_cmd_params = ["-b", "5"]

[workflow_config]
  use_chainlink_cli = true
  use_existing = false

  [workflow_config.chainlink_cli]
    folder_location = "/Users/bartektofel/Downloads/workflow_test"
    compile = true

  [workflow_config.existing]
    binary_url = "https://gist.githubusercontent.com/Tofel/3949a5537557c3e2d07524b1a0c857a0/raw/3f7dcbc91fbdb67d598ee0949c03965a771888a3/binary.wasm.br"

[nodeset]
  nodes = 5
  override_mode = "each"

[nodeset.db]
  image = "postgres:15.6"

  [[nodeset.node_specs]]

    [nodeset.node_specs.node]
      docker_ctx = "../.."
      docker_file = "plugins/chainlink.Dockerfile"
      user_config_overrides = """
      [Feature]
			LogPoller = true

			[OCR2]
			Enabled = true
			DatabaseTimeout = '1s'

			[P2P.V2]
			Enabled = true
			ListenAddresses = ['0.0.0.0:5001']
      """

  [[nodeset.node_specs]]

    [nodeset.node_specs.node]
      capabilities = ["./cron-linux-amd64"]
      docker_ctx = "../.."
      docker_file = "plugins/chainlink.Dockerfile"
      user_config_overrides = """
      [Feature]
			LogPoller = true

			[OCR2]
			Enabled = true
			DatabaseTimeout = '1s'

			[P2P.V2]
			Enabled = true
			ListenAddresses = ['0.0.0.0:5001']
      """

  [[nodeset.node_specs]]

    [nodeset.node_specs.node]
      capabilities = ["./cron-linux-amd64"]
      docker_ctx = "../.."
      docker_file = "plugins/chainlink.Dockerfile"
      user_config_overrides = """
      [Feature]
			LogPoller = true

			[OCR2]
			Enabled = true
			DatabaseTimeout = '1s'

			[P2P.V2]
			Enabled = true
			ListenAddresses = ['0.0.0.0:5001']
      """

  [[nodeset.node_specs]]

    [nodeset.node_specs.node]
      capabilities = ["./cron-linux-amd64"]
      docker_ctx = "../.."
      docker_file = "plugins/chainlink.Dockerfile"
      user_config_overrides = """
      [Feature]
			LogPoller = true

			[OCR2]
			Enabled = true
			DatabaseTimeout = '1s'

			[P2P.V2]
			Enabled = true
			ListenAddresses = ['0.0.0.0:5001']
      """

  [[nodeset.node_specs]]

    [nodeset.node_specs.node]
      capabilities = ["./cron-linux-amd64"]
      docker_ctx = "../.."
      docker_file = "plugins/chainlink.Dockerfile"
      user_config_overrides = """
      [Feature]
			LogPoller = true

			[OCR2]
			Enabled = true
			DatabaseTimeout = '1s'

			[P2P.V2]
			Enabled = true
			ListenAddresses = ['0.0.0.0:5001']
      """
