[blockchain_a]
type = 'anvil'
image = 'f4hrenh9it/foundry:latest'
pull_image = false
port = '8545'
port_ws = ''
chain_id = '1337'
docker_cmd_params = ['-b', '5']
public_key = ''
contracts_dir = ''

[blockchain_a.out]
use_cache = true
family = 'evm'
container_name = 'blockchain-node-ba2f0'
chain_id = '1337'

[[blockchain_a.out.nodes]]
ws_url = 'ws://127.0.0.1:8545'
http_url = 'http://127.0.0.1:8545'
docker_internal_ws_url = 'ws://blockchain-node-ba2f0:8545'
docker_internal_http_url = 'http://blockchain-node-ba2f0:8545'

[nodeset]
nodes = 5
http_port_range_start = 0
p2p_port_range_start = 0
dlv_port_range_start = 0
override_mode = 'each'

[nodeset.db]
image = 'postgres:15.6'
port = 0
name = ''
volume_name = ''
databases = 5
jd_database = false
pull_image = false

[[nodeset.node_specs]]
[nodeset.node_specs.node]
image = ''
name = ''
docker_file = 'plugins/chainlink.Dockerfile'
docker_ctx = '../..'
pull_image = false
capabilities = ['./streams-linux-amd64', './cron-linux-amd64']
capabilities_container_dir = ''
test_config_overrides = "\n\t\t\t\t[Feature]\n\t\t\t\tLogPoller = true\n\n\t\t\t\t[OCR2]\n\t\t\t\tEnabled = true\n\t\t\t\tDatabaseTimeout = '1s'\n\n\t\t\t\t[P2P.V2]\n\t\t\t\tEnabled = true\n\t\t\t\tListenAddresses = ['0.0.0.0:5001']\n\t\t\t\tDefaultBootstrappers = ['12D3KooWHnPLxdrpqCfTuy98sk6ZbN1aRwWYZWRoaJaHTppYJpxn@localhost:5001']\n\n\t\t\t\t[Capabilities.Peering.V2]\n\t\t\t\tEnabled = true\n\t\t\t\tListenAddresses = ['0.0.0.0:6690']\n\t\t\t\tDefaultBootstrappers = ['12D3KooWHnPLxdrpqCfTuy98sk6ZbN1aRwWYZWRoaJaHTppYJpxn@localhost:6690']\n\n\t\t\t\t# This is needed for the target capability to be initialized\n\t\t\t\t[[EVM]]\n\t\t\t\tChainID = '1337'\n\n\t\t\t\t[[EVM.Nodes]]\n\t\t\t\tName = 'anvil'\n\t\t\t\tWSURL = 'ws://blockchain-node-ba2f0:8545'\n\t\t\t\tHTTPURL = 'http://blockchain-node-ba2f0:8545'\n\n\t\t\t\t[EVM.Workflow]\n\t\t\t\tFromAddress = '0x7095A8B3eac565787b993973A0B303C56564a196'\n\t\t\t\tForwarderAddress = '0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9'\n\t\t\t\tGasLimitDefault = 400_000\n\n\t\t\t\t[Capabilities.ExternalRegistry]\n\t\t\t\tAddress = '0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512'\n\t\t\t\tNetworkID = 'evm'\n\t\t\t\tChainID = '1337'\n\n\t\t\t\t[Capabilities.WorkflowRegistry]\n\t\t\t\tAddress = \"0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9\"\n\t\t\t\tNetworkID = \"evm\"\n\t\t\t\tChainID = \"1337\"\n\n\t\t\t\t[Capabilities.GatewayConnector]\n\t\t\t\tDonID = \"1\"\n\t\t\t\tChainIDForNodeKey = \"1337\"\n\t\t\t\tNodeAddress = '0x7095A8B3eac565787b993973A0B303C56564a196'\n\n\t\t\t\t[[Capabilities.GatewayConnector.Gateways]]\n\t\t\t\tId = \"por_gateway\"\n\t\t\t\tURL = \"ws://node4:5003/node\"\n\t\t\t"
user_config_overrides = "      [Feature]\n\t\t\tLogPoller = true\n\n\t\t\t[OCR2]\n\t\t\tEnabled = true\n\t\t\tDatabaseTimeout = '1s'\n\n\t\t\t[P2P.V2]\n\t\t\tEnabled = true\n\t\t\tListenAddresses = ['0.0.0.0:5001']\n      "
test_secrets_overrides = ''
user_secrets_overrides = ''
port = 0
p2p_port = 0
custom_ports = []
debugger_port = 0

[[nodeset.node_specs]]
[nodeset.node_specs.node]
image = ''
name = ''
docker_file = 'plugins/chainlink.Dockerfile'
docker_ctx = '../..'
pull_image = false
capabilities = ['./streams-linux-amd64', './cron-linux-amd64']
capabilities_container_dir = ''
test_config_overrides = "\n\t\t\t\t[Feature]\n\t\t\t\tLogPoller = true\n\n\t\t\t\t[OCR2]\n\t\t\t\tEnabled = true\n\t\t\t\tDatabaseTimeout = '1s'\n\n\t\t\t\t[P2P.V2]\n\t\t\t\tEnabled = true\n\t\t\t\tListenAddresses = ['0.0.0.0:5001']\n\t\t\t\tDefaultBootstrappers = ['12D3KooWHnPLxdrpqCfTuy98sk6ZbN1aRwWYZWRoaJaHTppYJpxn@localhost:5001']\n\n\t\t\t\t[Capabilities.Peering.V2]\n\t\t\t\tEnabled = true\n\t\t\t\tListenAddresses = ['0.0.0.0:6690']\n\t\t\t\tDefaultBootstrappers = ['12D3KooWHnPLxdrpqCfTuy98sk6ZbN1aRwWYZWRoaJaHTppYJpxn@localhost:6690']\n\n\t\t\t\t# This is needed for the target capability to be initialized\n\t\t\t\t[[EVM]]\n\t\t\t\tChainID = '1337'\n\n\t\t\t\t[[EVM.Nodes]]\n\t\t\t\tName = 'anvil'\n\t\t\t\tWSURL = 'ws://blockchain-node-ba2f0:8545'\n\t\t\t\tHTTPURL = 'http://blockchain-node-ba2f0:8545'\n\n\t\t\t\t[EVM.Workflow]\n\t\t\t\tFromAddress = '0x9F6F083E6131c0e3301ed6F34E155126d69Ee1eb'\n\t\t\t\tForwarderAddress = '0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9'\n\t\t\t\tGasLimitDefault = 400_000\n\n\t\t\t\t[Capabilities.ExternalRegistry]\n\t\t\t\tAddress = '0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512'\n\t\t\t\tNetworkID = 'evm'\n\t\t\t\tChainID = '1337'\n\n\t\t\t\t[Capabilities.WorkflowRegistry]\n\t\t\t\tAddress = \"0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9\"\n\t\t\t\tNetworkID = \"evm\"\n\t\t\t\tChainID = \"1337\"\n\n\t\t\t\t[Capabilities.GatewayConnector]\n\t\t\t\tDonID = \"1\"\n\t\t\t\tChainIDForNodeKey = \"1337\"\n\t\t\t\tNodeAddress = '0x9F6F083E6131c0e3301ed6F34E155126d69Ee1eb'\n\n\t\t\t\t[[Capabilities.GatewayConnector.Gateways]]\n\t\t\t\tId = \"por_gateway\"\n\t\t\t\tURL = \"ws://node4:5003/node\"\n\t\t\t"
user_config_overrides = "      [Feature]\n\t\t\tLogPoller = true\n\n\t\t\t[OCR2]\n\t\t\tEnabled = true\n\t\t\tDatabaseTimeout = '1s'\n\n\t\t\t[P2P.V2]\n\t\t\tEnabled = true\n\t\t\tListenAddresses = ['0.0.0.0:5001']\n      "
test_secrets_overrides = ''
user_secrets_overrides = ''
port = 0
p2p_port = 0
custom_ports = []
debugger_port = 0

[[nodeset.node_specs]]
[nodeset.node_specs.node]
image = ''
name = ''
docker_file = 'plugins/chainlink.Dockerfile'
docker_ctx = '../..'
pull_image = false
capabilities = ['./streams-linux-amd64', './cron-linux-amd64']
capabilities_container_dir = ''
test_config_overrides = "\n\t\t\t\t[Feature]\n\t\t\t\tLogPoller = true\n\n\t\t\t\t[OCR2]\n\t\t\t\tEnabled = true\n\t\t\t\tDatabaseTimeout = '1s'\n\n\t\t\t\t[P2P.V2]\n\t\t\t\tEnabled = true\n\t\t\t\tListenAddresses = ['0.0.0.0:5001']\n\t\t\t\tDefaultBootstrappers = ['12D3KooWHnPLxdrpqCfTuy98sk6ZbN1aRwWYZWRoaJaHTppYJpxn@localhost:5001']\n\n\t\t\t\t[Capabilities.Peering.V2]\n\t\t\t\tEnabled = true\n\t\t\t\tListenAddresses = ['0.0.0.0:6690']\n\t\t\t\tDefaultBootstrappers = ['12D3KooWHnPLxdrpqCfTuy98sk6ZbN1aRwWYZWRoaJaHTppYJpxn@localhost:6690']\n\n\t\t\t\t# This is needed for the target capability to be initialized\n\t\t\t\t[[EVM]]\n\t\t\t\tChainID = '1337'\n\n\t\t\t\t[[EVM.Nodes]]\n\t\t\t\tName = 'anvil'\n\t\t\t\tWSURL = 'ws://blockchain-node-ba2f0:8545'\n\t\t\t\tHTTPURL = 'http://blockchain-node-ba2f0:8545'\n\n\t\t\t\t[EVM.Workflow]\n\t\t\t\tFromAddress = '0x355a49b94cDf8b13F02d61fDAea07Bf0dD1C8C94'\n\t\t\t\tForwarderAddress = '0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9'\n\t\t\t\tGasLimitDefault = 400_000\n\n\t\t\t\t[Capabilities.ExternalRegistry]\n\t\t\t\tAddress = '0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512'\n\t\t\t\tNetworkID = 'evm'\n\t\t\t\tChainID = '1337'\n\n\t\t\t\t[Capabilities.WorkflowRegistry]\n\t\t\t\tAddress = \"0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9\"\n\t\t\t\tNetworkID = \"evm\"\n\t\t\t\tChainID = \"1337\"\n\n\t\t\t\t[Capabilities.GatewayConnector]\n\t\t\t\tDonID = \"1\"\n\t\t\t\tChainIDForNodeKey = \"1337\"\n\t\t\t\tNodeAddress = '0x355a49b94cDf8b13F02d61fDAea07Bf0dD1C8C94'\n\n\t\t\t\t[[Capabilities.GatewayConnector.Gateways]]\n\t\t\t\tId = \"por_gateway\"\n\t\t\t\tURL = \"ws://node4:5003/node\"\n\t\t\t"
user_config_overrides = "      [Feature]\n\t\t\tLogPoller = true\n\n\t\t\t[OCR2]\n\t\t\tEnabled = true\n\t\t\tDatabaseTimeout = '1s'\n\n\t\t\t[P2P.V2]\n\t\t\tEnabled = true\n\t\t\tListenAddresses = ['0.0.0.0:5001']\n      "
test_secrets_overrides = ''
user_secrets_overrides = ''
port = 0
p2p_port = 0
custom_ports = []
debugger_port = 0

[[nodeset.node_specs]]
[nodeset.node_specs.node]
image = ''
name = ''
docker_file = 'plugins/chainlink.Dockerfile'
docker_ctx = '../..'
pull_image = false
capabilities = ['./streams-linux-amd64', './cron-linux-amd64']
capabilities_container_dir = ''
test_config_overrides = "\n\t\t\t\t[Feature]\n\t\t\t\tLogPoller = true\n\n\t\t\t\t[OCR2]\n\t\t\t\tEnabled = true\n\t\t\t\tDatabaseTimeout = '1s'\n\n\t\t\t\t[P2P.V2]\n\t\t\t\tEnabled = true\n\t\t\t\tListenAddresses = ['0.0.0.0:5001']\n\t\t\t\tDefaultBootstrappers = ['12D3KooWHnPLxdrpqCfTuy98sk6ZbN1aRwWYZWRoaJaHTppYJpxn@localhost:5001']\n\n\t\t\t\t[Capabilities.Peering.V2]\n\t\t\t\tEnabled = true\n\t\t\t\tListenAddresses = ['0.0.0.0:6690']\n\t\t\t\tDefaultBootstrappers = ['12D3KooWHnPLxdrpqCfTuy98sk6ZbN1aRwWYZWRoaJaHTppYJpxn@localhost:6690']\n\n\t\t\t\t# This is needed for the target capability to be initialized\n\t\t\t\t[[EVM]]\n\t\t\t\tChainID = '1337'\n\n\t\t\t\t[[EVM.Nodes]]\n\t\t\t\tName = 'anvil'\n\t\t\t\tWSURL = 'ws://blockchain-node-ba2f0:8545'\n\t\t\t\tHTTPURL = 'http://blockchain-node-ba2f0:8545'\n\n\t\t\t\t[EVM.Workflow]\n\t\t\t\tFromAddress = '0x6661cfFFD41fA1bF34AF379adaC5754d410E5938'\n\t\t\t\tForwarderAddress = '0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9'\n\t\t\t\tGasLimitDefault = 400_000\n\n\t\t\t\t[Capabilities.ExternalRegistry]\n\t\t\t\tAddress = '0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512'\n\t\t\t\tNetworkID = 'evm'\n\t\t\t\tChainID = '1337'\n\n\t\t\t\t[Capabilities.WorkflowRegistry]\n\t\t\t\tAddress = \"0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9\"\n\t\t\t\tNetworkID = \"evm\"\n\t\t\t\tChainID = \"1337\"\n\n\t\t\t\t[Capabilities.GatewayConnector]\n\t\t\t\tDonID = \"1\"\n\t\t\t\tChainIDForNodeKey = \"1337\"\n\t\t\t\tNodeAddress = '0x6661cfFFD41fA1bF34AF379adaC5754d410E5938'\n\n\t\t\t\t[[Capabilities.GatewayConnector.Gateways]]\n\t\t\t\tId = \"por_gateway\"\n\t\t\t\tURL = \"ws://node4:5003/node\"\n\t\t\t"
user_config_overrides = "      [Feature]\n\t\t\tLogPoller = true\n\n\t\t\t[OCR2]\n\t\t\tEnabled = true\n\t\t\tDatabaseTimeout = '1s'\n\n\t\t\t[P2P.V2]\n\t\t\tEnabled = true\n\t\t\tListenAddresses = ['0.0.0.0:5001']\n      "
test_secrets_overrides = ''
user_secrets_overrides = ''
port = 0
p2p_port = 0
custom_ports = []
debugger_port = 0

[[nodeset.node_specs]]
[nodeset.node_specs.node]
image = ''
name = ''
docker_file = 'plugins/chainlink.Dockerfile'
docker_ctx = '../..'
pull_image = false
capabilities = []
capabilities_container_dir = ''
test_config_overrides = "\n\t\t\t\t[Feature]\n\t\t\t\tLogPoller = true\n\n\t\t\t\t[OCR2]\n\t\t\t\tEnabled = true\n\t\t\t\tDatabaseTimeout = '1s'\n\n\t\t\t\t[P2P.V2]\n\t\t\t\tEnabled = true\n\t\t\t\tListenAddresses = ['0.0.0.0:5001']\n\t\t\t\tDefaultBootstrappers = ['12D3KooWHnPLxdrpqCfTuy98sk6ZbN1aRwWYZWRoaJaHTppYJpxn@localhost:5001']\n\n\t\t\t\t[Capabilities.Peering.V2]\n\t\t\t\tEnabled = true\n\t\t\t\tListenAddresses = ['0.0.0.0:6690']\n\t\t\t\tDefaultBootstrappers = ['12D3KooWHnPLxdrpqCfTuy98sk6ZbN1aRwWYZWRoaJaHTppYJpxn@localhost:6690']\n\n\t\t\t\t# This is needed for the target capability to be initialized\n\t\t\t\t[[EVM]]\n\t\t\t\tChainID = '1337'\n\n\t\t\t\t[[EVM.Nodes]]\n\t\t\t\tName = 'anvil'\n\t\t\t\tWSURL = 'ws://blockchain-node-ba2f0:8545'\n\t\t\t\tHTTPURL = 'http://blockchain-node-ba2f0:8545'\n\t\t\t"
user_config_overrides = "      [Feature]\n\t\t\tLogPoller = true\n\n\t\t\t[OCR2]\n\t\t\tEnabled = true\n\t\t\tDatabaseTimeout = '1s'\n\n\t\t\t[P2P.V2]\n\t\t\tEnabled = true\n\t\t\tListenAddresses = ['0.0.0.0:5001']\n      "
test_secrets_overrides = ''
user_secrets_overrides = ''
port = 0
p2p_port = 0
custom_ports = []
debugger_port = 0

[nodeset.out]
use_cache = true

[nodeset.out.db_out]
url = 'postgresql://chainlink:thispasswordislongenough@127.0.0.1:13000/chainlink?sslmode=disable'
container_name = 'ns-postgresql-1a0b5'
docker_internal_url = 'postgresql://chainlink:thispasswordislongenough@ns-postgresql-1a0b5:5432/chainlink?sslmode=disable'
jd_url = ''
jd_docker_internal_url = ''

[[nodeset.out.cl_nodes]]
use_cache = true

[nodeset.out.cl_nodes.node]
api_auth_user = 'notreal@fakeemail.ch'
api_auth_password = 'fj293fbBnlQ!f9vNs'
container_name = 'node0'
url = 'http://127.0.0.1:10000'
docker_internal_url = 'http://node0:6688'
p2p_docker_internal_url = 'http://node0:6690'
internal_ip = '172.18.0.8'

[nodeset.out.cl_nodes.postgresql]
url = 'postgresql://chainlink:thispasswordislongenough@127.0.0.1:13000/db_0?sslmode=disable'
container_name = ''
docker_internal_url = 'postgresql://chainlink:thispasswordislongenough@ns-postgresql-1a0b5:5432/db_0?sslmode=disable'
jd_url = ''
jd_docker_internal_url = ''

[[nodeset.out.cl_nodes]]
use_cache = true

[nodeset.out.cl_nodes.node]
api_auth_user = 'notreal@fakeemail.ch'
api_auth_password = 'fj293fbBnlQ!f9vNs'
container_name = 'node1'
url = 'http://127.0.0.1:10001'
docker_internal_url = 'http://node1:6688'
p2p_docker_internal_url = 'http://node1:6690'
internal_ip = '172.18.0.7'

[nodeset.out.cl_nodes.postgresql]
url = 'postgresql://chainlink:thispasswordislongenough@127.0.0.1:13000/db_1?sslmode=disable'
container_name = ''
docker_internal_url = 'postgresql://chainlink:thispasswordislongenough@ns-postgresql-1a0b5:5432/db_1?sslmode=disable'
jd_url = ''
jd_docker_internal_url = ''

[[nodeset.out.cl_nodes]]
use_cache = true

[nodeset.out.cl_nodes.node]
api_auth_user = 'notreal@fakeemail.ch'
api_auth_password = 'fj293fbBnlQ!f9vNs'
container_name = 'node2'
url = 'http://127.0.0.1:10002'
docker_internal_url = 'http://node2:6688'
p2p_docker_internal_url = 'http://node2:6690'
internal_ip = '172.18.0.5'

[nodeset.out.cl_nodes.postgresql]
url = 'postgresql://chainlink:thispasswordislongenough@127.0.0.1:13000/db_2?sslmode=disable'
container_name = ''
docker_internal_url = 'postgresql://chainlink:thispasswordislongenough@ns-postgresql-1a0b5:5432/db_2?sslmode=disable'
jd_url = ''
jd_docker_internal_url = ''

[[nodeset.out.cl_nodes]]
use_cache = true

[nodeset.out.cl_nodes.node]
api_auth_user = 'notreal@fakeemail.ch'
api_auth_password = 'fj293fbBnlQ!f9vNs'
container_name = 'node3'
url = 'http://127.0.0.1:10003'
docker_internal_url = 'http://node3:6688'
p2p_docker_internal_url = 'http://node3:6690'
internal_ip = '172.18.0.6'

[nodeset.out.cl_nodes.postgresql]
url = 'postgresql://chainlink:thispasswordislongenough@127.0.0.1:13000/db_3?sslmode=disable'
container_name = ''
docker_internal_url = 'postgresql://chainlink:thispasswordislongenough@ns-postgresql-1a0b5:5432/db_3?sslmode=disable'
jd_url = ''
jd_docker_internal_url = ''

[[nodeset.out.cl_nodes]]
use_cache = true

[nodeset.out.cl_nodes.node]
api_auth_user = 'notreal@fakeemail.ch'
api_auth_password = 'fj293fbBnlQ!f9vNs'
container_name = 'node4'
url = 'http://127.0.0.1:10004'
docker_internal_url = 'http://node4:6688'
p2p_docker_internal_url = 'http://node4:6690'
internal_ip = '172.18.0.4'

[nodeset.out.cl_nodes.postgresql]
url = 'postgresql://chainlink:thispasswordislongenough@127.0.0.1:13000/db_4?sslmode=disable'
container_name = ''
docker_internal_url = 'postgresql://chainlink:thispasswordislongenough@ns-postgresql-1a0b5:5432/db_4?sslmode=disable'
jd_url = ''
jd_docker_internal_url = ''
