# billing service
[billing_platform_service]
  compose_file='https://raw.githubusercontent.com/smartcontractkit/chainlink-testing-framework/9ad8f2626fa6ff37997d00ac90d1fc64bff2847d/framework/components/dockercompose/billing_platform_service/docker-compose.yml'