# beholder
[chip_ingress]
  compose_file='https://github.com/smartcontractkit/chainlink-testing-framework/blob/main/framework/components/dockercompose/chip_ingress_set/docker-compose.yml'

[kafka]
  topics=['cre']