[general]
aws_profile = "sdlc"
min_gh_cli_version = "v2.50.0"
ctf_version = "0.10.30"

[job_distributor.build_config]
repository = "https://github.com/smartcontractkit/job-distributor"
branch = "v0.12.7"
dockerfile = "e2e/Dockerfile.e2e"
docker_ctx = "."
local_image = "job-distributor:0.12.7"

[job_distributor.pull_config]
local_image = "job-distributor:0.12.7"
ecr_image = "{{.ECR}}/job-distributor:0.12.7"

[chip_ingress.build_config]
repository = "https://github.com/smartcontractkit/atlas"
branch = "master"
commit = "bbac3c825b061546980fa9d7dc0f3e8c34347bcf"
dockerfile = "chip-ingress/Dockerfile"
docker_ctx = "chip-ingress"
local_image = "chip-ingress:local-cre"
pre_run = "pushd chip-ingress && go mod vendor && popd"

[chip_ingress.pull_config]
local_image = "chip-ingress:local-cre"
ecr_image = "{{.ECR}}/atlas-chip-ingress:bbac3c825b061546980fa9d7dc0f3e8c34347bcf"

[billing_platform_service.build_config]
repository = "https://github.com/smartcontractkit/billing-platform-service"
branch = "main"
require_github_token = true
dockerfile = "./Dockerfile"
docker_ctx = "."
local_image = "billing-platform-service:local-cre"

[billing_platform_service.pull_config]
local_image = "billing-platform-service:local-cre"
ecr_image = "{{.ECR}}/billing-platform-service:1.36.1"

[capabilities]
target_path = "./binaries"
make_commands = ["install-plugins-public", "install-plugins-private", "install-plugins-local"]