# if you want to use APECHAIN_MAINNET
[Network]
selected_networks = ["APECHAIN_MAINNET"]
# soak test specific configuration
[Soak.Common]
chainlink_node_funding = 10 # Funding per node
# Note this is for when you are running OCR2 tests
# To run OCR1 tests use [Soak.OCR] instead
[Soak.OCR2]
# To run OCR1 tests use [Soak.OCR.Common] instead
[Soak.OCR2.Common]
test_duration = "24h" # Full duration the test will run 1440 - 1 day, 7200 - 5 days
# To run OCR1 tests use [Soak.OCR.Soak] instead
[Soak.OCR2.Soak]
time_between_rounds = "5m" # Default 5 mins for a 1 day, 10 mins for a 5 day
[OCR2.Common]
number_of_contracts = 2
[Seth]
experiments_enabled = ["slow_funds_return"]
# Recommended: Remove this table if you would like SETH to use the DEFAULT config or if the chain 
# is already added to CTF and you do not need to override any values.
# If the chain has already been added to CTF you can use this table to override any of the keys.
# If the chain has NOT been added to CTF you can use this table to pass the chain details to CTF.
[Network.EVMNetworks.APECHAIN_MAINNET]
evm_name = "APECHAIN_MAINNET"
evm_chain_id = 33139
client_implementation = "Ethereum"
evm_simulated = false
evm_chainlink_transaction_limit = 5000
evm_minimum_confirmations = 1
evm_gas_estimation_buffer = 10000
evm_supports_eip1559 = true
evm_default_gas_limit = 6000000