[Network]
selected_networks = ["Botanix_testnet"]

# soak test specific configuration
[Soak.Common]
chainlink_node_funding = 0.2 # Funding per node

# Note this is for when you are running OCR2 tests
# To run OCR1 tests use [Soak.OCR] instead
[Soak.OCR2]

# To run OCR1 tests use [Soak.OCR.Common] instead
[Soak.OCR2.Common]
test_duration = "24h" # Full duration the test will run 1440 - 1 day, 7200 - 5 days

# To run OCR1 tests use [Soak.OCR.Soak] instead
[Soak.OCR2.Soak]
time_between_rounds = "5m" # Default 5 mins for a 1 day, 10 mins for a 5 day

[OCR2.Common]
number_of_contracts = 2

[Seth]
experiments_enabled = ["slow_funds_return"]


[NodeConfig.ChainConfigTOMLByChainID]
# Polygon Katana Tatara 
3636 = """
FinalityTagEnabled = false
FinalityDepth = 10 # instant finality so adding buffer
NonceAutoSync = false

[EVM.HeadTracker]
FinalityTagBypass = false

[EVM.GasEstimator]
EIP1559DynamicFees = true

[EVM.GasEstimator.BlockHistory]
# Default is 24, which leads to bumpy gas prices. In CCIP
# we want to smooth out the gas prices, so we increase the sample size.
BlockHistorySize = 200

[EVM.NodePool]
NewHeadsPollInterval = '4s'
"""

[Network.EVMNetworks.Botanix_testnet]
evm_name = "Botanix_testnet"
evm_chain_id = 3636
client_implementation = "Ethereum"
evm_simulated = false
evm_chainlink_transaction_limit = 5000
evm_minimum_confirmations = 1
evm_gas_estimation_buffer = 10000
evm_supports_eip1559 = true
evm_default_gas_limit = 6000000
