[Network]
selected_networks = ["BSC_TESTNET"]

[Soak.Common]
chainlink_node_funding = 0.1

[Soak.OCR2]
[Soak.OCR2.Common]
test_duration = "2h"

[Soak.OCR2.Soak]
time_between_rounds = "2m"

[OCR2.Common]
number_of_contracts = 2

[Seth]
experiments_enabled = ["slow_funds_return"]
