# if you want to use HEMI_TESTNET
[Network]
selected_networks = ["HEMI_TESTNET"]
# soak test specific configuration
[Soak.Common]
chainlink_node_funding = 0.5 # Funding per node
# Note this is for when you are running OCR2 tests
# To run OCR1 tests use [Soak.OCR] instead
[Soak.OCR2]
# To run OCR1 tests use [Soak.OCR.Common] instead
[Soak.OCR2.Common]
test_duration = "24h" # Full duration the test will run 1440 - 1 day, 7200 - 5 days
# To run OCR1 tests use [Soak.OCR.Soak] instead
[Soak.OCR2.Soak]
time_between_rounds = "5m" # Default 5 mins for a 1 day, 10 mins for a 5 day
[OCR2.Common]
number_of_contracts = 2
[Seth]
experiments_enabled = ["slow_funds_return"]
# Recommended: Remove this table if you would like SETH to use the DEFAULT config or if the chain 
# is already added to CTF and you do not need to override any values.
# If the chain has already been added to CTF you can use this table to override any of the keys.
# If the chain has NOT been added to CTF you can use this table to pass the chain details to CTF.
[Network.EVMNetworks.HEMI_TESTNET]
evm_name = "HEMI_TESTNET"
evm_chain_id = 743111
client_implementation = "Ethereum"
evm_simulated = false
evm_chainlink_transaction_limit = 5000
evm_minimum_confirmations = 1
evm_gas_estimation_buffer = 10000
evm_supports_eip1559 = true
evm_default_gas_limit = 6000000

# Chainlink node TOML config
[NodeConfig]
BaseConfigTOML = """
[Feature]
FeedsManager = true
LogPoller = true
UICSAKeys = true

[Log]
Level = 'debug'
JSONConsole = true

[Log.File]
MaxSize = '0b'

[WebServer]
AllowOrigins = '*'
HTTPPort = 6688
SecureCookies = false
HTTPWriteTimeout = '3m'
SessionTimeout = '999h0m0s'

[WebServer.RateLimit]
Authenticated = 2000
Unauthenticated = 1000

[WebServer.TLS]
HTTPSPort = 0

[Database]
MaxIdleConns = 20
MaxOpenConns = 40
MigrateOnStartup = true

[OCR2]
Enabled = true

[P2P]
[P2P.V2]
ListenAddresses = ['0.0.0.0:6690']
"""

# override config toml related to EVMNode configs for chainlink nodes; applicable to all EVM node configs in chainlink toml
CommonChainConfigTOML = """
LogBroadcasterEnabled = false

[NodePool]
NewHeadsPollInterval = '6s'
"""