[Network]
selected_networks = ["LENS_SEPOLIA"]

[Soak.Common]
chainlink_node_funding = 10

[Soak.OCR]
[Soak.OCR.Common]
test_duration = "24h"

[Soak.OCR.Soak]
time_between_rounds = "5m"

[OCR.Common]
number_of_contracts = 2

[OCR.Contracts]
use = true
link_token = "0x9f55307967D09C73879548431bC1f3DdaE77d029"
offchain_aggregators = ["0x10F938FED31C006637Fc26887eFD43928Aa0d3a1"]

[Network.EVMNetworks.LENS_SEPOLIA]
evm_name = "LENS_SEPOLIA"
evm_chain_id = 37111
client_implementation = "Ethereum"
evm_simulated = false
evm_chainlink_transaction_limit = 5000
evm_minimum_confirmations = 1
evm_gas_estimation_buffer = 100000
evm_supports_eip1559 = true
evm_default_gas_limit = 6000000
