[Network]
selected_networks = ["PLUME_DEVNET"]

[Soak.Common]
chainlink_node_funding = 0.3

[Soak.OCR2]
[Soak.OCR2.Common]
test_duration = "4h"

[Soak.OCR2.Soak]
time_between_rounds = "5m"

[OCR2.Common]
number_of_contracts = 2

[Network.EVMNetworks.PLUME_DEVNET]
evm_name = "plume-devnet"
evm_chain_id = 98864
client_implementation = "Ethereum"
evm_simulated = false
evm_chainlink_transaction_limit = 5000
evm_minimum_confirmations = 1
evm_gas_estimation_buffer = 10000
evm_supports_eip1559 = false
evm_default_gas_limit = 6000000
