[Network]
selected_networks = ["0G_TESTNET_NEWTON"]

[Soak.Common]
chainlink_node_funding = 2

[Soak.OCR]
[Soak.OCR.Common]
test_duration = "4h"

[Soak.OCR.Soak]
time_between_rounds = "5m"

[OCR.Common]
number_of_contracts = 2

[Network.EVMNetworks.0G_TESTNET_NEWTON]
evm_name = "0g-testnet-newton"
evm_chain_id = 16600
client_implementation = "Ethereum"
evm_simulated = false
evm_chainlink_transaction_limit = 5000
evm_minimum_confirmations = 1
evm_gas_estimation_buffer = 10000
evm_supports_eip1559 = false
evm_default_gas_limit = 6000000