[ChainlinkImage]
version = "3fed3fa40f5ee602018358318c80f78a36c63ae1"

[Network]
selected_networks = ["ARBITRUM_SEPOLIA"]

[Soak.Common]
chainlink_node_funding = 0.1

[Soak.OCR]
[Soak.OCR.Common]
test_duration = "1h"

[Soak.OCR.Soak]
time_between_rounds = "2m"

[OCR.Common]
number_of_contracts = 2

[Network.EVMNetworks.ARBITRUM_SEPOLIA]
evm_name = "ARBITRUM_SEPOLIA"
evm_chain_id = 421614
client_implementation = "Arbitrum"
evm_simulated = false
evm_chainlink_transaction_limit = 5000
evm_minimum_confirmations = 1
evm_gas_estimation_buffer = 100000
evm_supports_eip1559 = true
evm_default_gas_limit = 6000000

[[Seth.networks]]
name = "ARBITRUM_SEPOLIA"
chain_id = 421614
transaction_timeout = "10m"
transfer_gas_fee = 21_000
# legacy transactions
gas_price = 13_400_000_000
# EIP-1559 transactions
eip_1559_dynamic_fees = true
gas_fee_cap = 109_694_825_437
gas_tip_cap = 30_000_000_000
# if set to true we will estimate gas for every transaction
gas_price_estimation_enabled = true
# how many last blocks to use, when estimating gas for a transaction
gas_price_estimation_blocks = 500
# priority of the transaction, can be "fast", "standard" or "slow" (the higher the priority, the higher adjustment factor will be used for gas estimation) [default: "standard"]
gas_price_estimation_tx_priority = "standard"
