[Network]
selected_networks = ["CRONOS_ZKEVM_TESTNET_SEPOLIA"]

[Soak.Common]
chainlink_node_funding = 50

[Soak.OCR]
[Soak.OCR.Common]
test_duration = "4h"

[Soak.OCR.Soak]
time_between_rounds = "5m"

[OCR.Common]
number_of_contracts = 2

[OCR.Contracts]
use = true
link_token = "0x2750DBAaD91772c9C151abc760D253450168A3E6"
offchain_aggregators = ["0xCA892ac7428aDA3722F7b42b2629609d2D7Bf3Bb", "0xB0e9a35198e69e2e1226F98A6374608DC1b57014"]

[Network.EVMNetworks.CRONOS_ZKEVM_TESTNET_SEPOLIA]
evm_name = "cronos-zkevm-testnet-sepolia"
evm_chain_id = 240
client_implementation = "Ethereum"
evm_simulated = false
evm_chainlink_transaction_limit = 5000
evm_minimum_confirmations = 1
evm_gas_estimation_buffer = 10000
evm_supports_eip1559 = false
evm_default_gas_limit = 6000000