[ChainlinkImage]
version = "f85400a5318d4c16dbba0b79220d2f063797c0cd"

[Network]
selected_networks = ["LENS_SEPOLIA"]

[Soak.Common]
chainlink_node_funding = 500

[Soak.OCR]
[Soak.OCR.Common]
test_duration = "12h"

[Soak.OCR.Soak]
time_between_rounds = "10m"

[OCR.Common]
number_of_contracts = 2

[OCR.Contracts]
use = true
link_token = "0xEa07234ca51Fc2Ec87fc152D4dE6b2eBb25d65dE"
offchain_aggregators = ["0x5240f07f82C8Cb4df472c9c1fe8022Be23Ee6994", "0x89625FC0Dd6cD23a6DB93C832DBcaC12A3c84516"]

[Network.EVMNetworks.LENS_SEPOLIA]
evm_name = "LENS_SEPOLIA"
evm_chain_id = 37111
client_implementation = "Ethereum"
evm_simulated = false
evm_chainlink_transaction_limit = 5000
evm_minimum_confirmations = 1
evm_gas_estimation_buffer = 100000
evm_supports_eip1559 = false
evm_default_gas_limit = 6000000