[ChainlinkImage]
version = "061320eb3f0440536eddd0fe664d854b4b0f8bd8"

[Network]
selected_networks = ["LENS_SEPOLIA"]

[Soak.Common]
chainlink_node_funding = 500

[Soak.OCR]
[Soak.OCR.Common]
test_duration = "2h"

[Soak.OCR.Soak]
time_between_rounds = "5m"

[OCR.Common]
number_of_contracts = 2

[OCR.Contracts]
use = true
link_token = "0x647155BA65b6c658549b200f32De3802B5E08058"
offchain_aggregators = ["0x65cCB560dD714fE237E4122A4696Ae66fC401e51", "0x586F678Ce5497B3904ae8CF3808430B3b6ef1460"]

[Network.EVMNetworks.LENS_SEPOLIA]
evm_name = "LENS_SEPOLIA"
evm_chain_id = 37111
client_implementation = "Ethereum"
evm_simulated = false
evm_chainlink_transaction_limit = 5000
evm_minimum_confirmations = 1
evm_gas_estimation_buffer = 100000
evm_supports_eip1559 = false
evm_default_gas_limit = 6000000