[Network]
selected_networks = ["POLYGON_AMOY"]

[Soak.Common]
chainlink_node_funding = 60

[Soak.OCR]
[Soak.OCR.Common]
test_duration = "1h"

[Soak.OCR.Soak]
time_between_rounds = "30s"

[OCR.Common]
number_of_contracts = 2
