# if you want to use TREASURE_TOPAZ
[Network]
selected_networks = ["TREASURE_TOPAZ"]
# soak test specific configuration
[Soak.Common]
chainlink_node_funding = 500 # Funding per node
# Note this is for when you are running OCR2 tests
# To run OCR1 tests use [Soak.OCR] instead
[Soak.OCR]
# To run OCR1 tests use [Soak.OCR.Common] instead
[Soak.OCR.Common]
test_duration = "24h" # Full duration the test will run 1440 - 1 day, 7200 - 5 days
# To run OCR1 tests use [Soak.OCR.Soak] instead
[Soak.OCR.Soak]
time_between_rounds = "5m" # Default 5 mins for a 1 day, 10 mins for a 5 day
[OCR.Common]
number_of_contracts = 2
[OCR.Contracts]
use = true
link_token = "0xC71F8F64Ee9bd31F86467f8b52dda2d65089baA2"
offchain_aggregators = ["0xc75DfA2eD5A708d8479679980a54bF183E083BbC", "0x78CCE14602e765601cE0a4833AD53656113DFF16"]
[Seth]
experiments_enabled = ["slow_funds_return"]
# Recommended: Remove this table if you would like SETH to use the DEFAULT config or if the chain 
# is already added to CTF and you do not need to override any values.
# If the chain has already been added to CTF you can use this table to override any of the keys.
# If the chain has NOT been added to CTF you can use this table to pass the chain details to CTF.
[Network.EVMNetworks.TREASURE_TOPAZ]
evm_name = "TREASURE_TOPAZ"
evm_chain_id = 978658
client_implementation = "Ethereum"
evm_simulated = false
evm_chainlink_transaction_limit = 5000
evm_minimum_confirmations = 1
evm_gas_estimation_buffer = 10000
evm_supports_eip1559 = true
evm_default_gas_limit = 2500000000

[[Seth.networks]]
name = "TREASURE_TOPAZ"
transaction_timeout = "3m"
transfer_gas_fee = 5_000_000
gas_limit = 500_000_000
# legacy transactions
gas_price = 264_184_358_789
# EIP-1559 transactions
eip_1559_dynamic_fees = true
gas_fee_cap = 264_184_358_789
gas_tip_cap = 50_000_000
# if set to true we will estimate gas for every transaction
gas_price_estimation_enabled = true
# how many last blocks to use, when estimating gas for a transaction
gas_price_estimation_blocks = 200