ChainID = '421614'
FinalityDepth = 4350
ChainType = 'arbitrum'
FinalityTagEnabled = true
# Not sure why this is used or if it needs to be here (got it from https://github.com/smartcontractkit/ccip/commit/4c07f36580a6ad3efaece6147e2a2abf4bd63422)
LinkContractAddress = '0xE4aB69C077896252FAFBD49EFD26B5D171A32410'
NoNewHeadsThreshold = '0'
OCR.ContractConfirmations = 1
LogPollInterval = '1s'

[GasEstimator]
Mode = 'Arbitrum'
LimitMax = 1_000_000_000
# Arbitrum uses the suggested gas price, so we don't want to place any limits on the minimum
PriceMin = '0'
PriceDefault = '0.1 gwei'
PriceMax = '115792089237316195423570985008687907853269984665.640564039457584007913129639935 tether'
FeeCapDefault = '1000 gwei'
BumpThreshold = 5

[GasEstimator.BlockHistory]
# Force an error if someone set GAS_UPDATER_ENABLED=true by accident; we never want to run the block history estimator on arbitrum
BlockHistorySize = 0

[GasEstimator.DAOracle]
OracleType = 'arbitrum'

[NodePool]
SyncThreshold = 10

[OCR2.Automation]
GasLimit = 14500000
