ChainID = '81'
FinalityTagEnabled = true
FinalityDepth = 100
LogPollInterval = '6s'

[GasEstimator]
EIP1559DynamicFees = false
PriceMax = '100000 gwei'
LimitDefault = 8000000

[HeadTracker]
# FinalityDepth > 1k => FinalityTagBypass = false
# https://chainlink-core.slack.com/archives/C07RA1B58CC/p1730983397689179?thread_ts=1730908333.814809&cid=C07RA1B58CC
FinalityTagBypass = false
