ChainID = '4'
FinalityDepth = 50
LinkContractAddress = '0x01BE23585060835E02B77ef475b0Cc51aA1e0709'
MinContractPayment = '0.1 link'

[GasEstimator]
# TODO: EIP1559 on rinkeby has not been adequately tested, see:
# https://smartcontract-it.atlassian.net/browse/BCF-1420
EIP1559DynamicFees = false

[GasEstimator.BlockHistory]
BlockHistorySize = 4
TransactionPercentile = 50

[HeadTracker]
# FinalityDepth > 1k => FinalityTagBypass = false
# https://chainlink-core.slack.com/archives/C07RA1B58CC/p1730983397689179?thread_ts=1730908333.814809&cid=C07RA1B58CC
FinalityTagBypass = false
