ChainID = '3'
FinalityDepth = 50
LinkContractAddress = '0x20fE562d797A42Dcb3399062AE9546cd06f63280'
MinContractPayment = '0.1 link'

[GasEstimator]
EIP1559DynamicFees = true

[GasEstimator.BlockHistory]
BlockHistorySize = 4
TransactionPercentile = 50

[HeadTracker]
# FinalityDepth > 1k => FinalityTagBypass = false
# https://chainlink-core.slack.com/archives/C07RA1B58CC/p1730983397689179?thread_ts=1730908333.814809&cid=C07RA1B58CC
FinalityTagBypass = false
