ChainID = '11155111'
FinalityDepth = 50
FinalityTagEnabled = true
LinkContractAddress = '0x779877A7B0D9E8603169DdbD7836e478b4624789'
MinContractPayment = '0.1 link'

[GasEstimator]
EIP1559DynamicFees = true

[GasEstimator.BlockHistory]
BlockHistorySize = 4
TransactionPercentile = 50

[OCR2.Automation]
GasLimit = 10500000

[HeadTracker]
# FinalityDepth > 1k => FinalityTagBypass = false
# https://chainlink-core.slack.com/archives/C07RA1B58CC/p1730983397689179?thread_ts=1730908333.814809&cid=C07RA1B58CC
FinalityTagBypass = false
