ChainID = '5'
FinalityDepth = 50
LinkContractAddress = '0x326C977E6efc84E512bB9C30f76E30c160eD06FB'
MinContractPayment = '0.1 link'

[GasEstimator]
EIP1559DynamicFees = true

[GasEstimator.BlockHistory]
BlockHistorySize = 4
TransactionPercentile = 50

[HeadTracker]
# FinalityDepth > 1k => FinalityTagBypass = false
# https://chainlink-core.slack.com/archives/C07RA1B58CC/p1730983397689179?thread_ts=1730908333.814809&cid=C07RA1B58CC
FinalityTagBypass = false
