ChainID = '42'
FinalityDepth = 50
LinkContractAddress = '0xa36085F69e2889c224210F603D836748e7dC0088'
MinContractPayment = '0.1 link'
OperatorFactoryAddress = '0x8007e24251b1D2Fc518Eb843A701d9cD21fe0aA3'

[GasEstimator]
# FIXME: Kovan has strange behaviour with EIP1559, see:
# https://smartcontract-it.atlassian.net/browse/BCF-1420
EIP1559DynamicFees = false

[GasEstimator.BlockHistory]
BlockHistorySize = 4
TransactionPercentile = 50

[HeadTracker]
# FinalityDepth > 1k => FinalityTagBypass = false
# https://chainlink-core.slack.com/archives/C07RA1B58CC/p1730983397689179?thread_ts=1730908333.814809&cid=C07RA1B58CC
FinalityTagBypass = false
