ChainID = '250'
FinalityDepth = 50
LinkContractAddress = '0x6F43FF82CCA38001B6699a8AC47A2d0E66939407'
LogPollInterval = '1s'
NoNewHeadsThreshold = '30s'
RPCBlockQueryDelay = 2

[GasEstimator]
# Fantom network has been slow to include txs at times when using the BlockHistory estimator, and the recommendation is to use SuggestedPrice mode.
Mode = 'SuggestedPrice'

[OCR2.Automation]
GasLimit = 3800000

[HeadTracker]
# FinalityDepth > 1k => FinalityTagBypass = false
# https://chainlink-core.slack.com/archives/C07RA1B58CC/p1730983397689179?thread_ts=1730908333.814809&cid=C07RA1B58CC
FinalityTagBypass = false
