ChainID = '4002'
FinalityDepth = 50
LinkContractAddress = '0xfaFedb041c0DD4fA2Dc0d87a6B0979Ee6FA7af5F'
LogPollInterval = '1s'
# Fantom testnet only emits blocks when a new tx is received, so this method of liveness detection is not useful
NoNewHeadsThreshold = '0'
RPCBlockQueryDelay = 2

[GasEstimator]
Mode = 'SuggestedPrice'

[OCR2.Automation]
GasLimit = 3800000

[HeadTracker]
# FinalityDepth > 1k => FinalityTagBypass = false
# https://chainlink-core.slack.com/archives/C07RA1B58CC/p1730983397689179?thread_ts=1730908333.814809&cid=C07RA1B58CC
FinalityTagBypass = false
