ChainID = '10200'
# Gnoisis Finality is approx 8 minutes @ 12 blocks per minute, so 96 blocks
FinalityDepth = 100
ChainType = 'gnosis'
LogPollInterval = '5s'
FinalizedBlockOffset = 2
NoNewFinalizedHeadsThreshold = '2m'

[GasEstimator]
EIP1559DynamicFees = true
PriceMax = '500 gwei'

[HeadTracker]
# FinalityDepth > 1k => FinalityTagBypass = false
# https://chainlink-core.slack.com/archives/C07RA1B58CC/p1730983397689179?thread_ts=1730908333.814809&cid=C07RA1B58CC
FinalityTagBypass = false
