ChainID = '1666600000'
FinalityDepth = 50
LinkContractAddress = '0x218532a12a389a4a92fC0C5Fb22901D1c19198aA'
LogPollInterval = '2s'
MinIncomingConfirmations = 1
NoNewHeadsThreshold = '30s'

[GasEstimator]
PriceDefault = '5 gwei'

[HeadTracker]
# FinalityDepth > 1k => FinalityTagBypass = false
# https://chainlink-core.slack.com/archives/C07RA1B58CC/p1730983397689179?thread_ts=1730908333.814809&cid=C07RA1B58CC
FinalityTagBypass = false
