ChainID = '59144'
#3s block time ~ 20m finality based on committee decision
FinalityDepth = 600
# Blocks are only emitted when a transaction happens / no empty blocks
NoNewHeadsThreshold = '0'

[GasEstimator]
BumpPercent = 40
PriceMin = '400 mwei'

[Transactions]
# increase resend time to align with finality
ResendAfterThreshold = '3m'

# set greater than finality depth
[HeadTracker]
HistoryDepth = 350
# FinalityDepth > 1k => FinalityTagBypass = false
# https://chainlink-core.slack.com/archives/C07RA1B58CC/p1730983397689179?thread_ts=1730908333.814809&cid=C07RA1B58CC
FinalityTagBypass = false
