ChainID = '59140'
# Block time 12s, finality < 3m
FinalityDepth = 15
# Blocks are only emitted when a transaction happens / no empty blocks
NoNewHeadsThreshold = '0'

[GasEstimator]
BumpPercent = 40

[Transactions]
# increase resend time to align with finality
ResendAfterThreshold = '3m'

[HeadTracker]
# FinalityDepth > 1k => FinalityTagBypass = false
# https://chainlink-core.slack.com/archives/C07RA1B58CC/p1730983397689179?thread_ts=1730908333.814809&cid=C07RA1B58CC
FinalityTagBypass = false
