ChainID = '10143'
# finality_depth was: 0
FinalityDepth = 10
# block_time was:  1s, adding 1 second buffer  
LogPollInterval = '2s'
LogBroadcasterEnabled = false
FinalityTagEnabled = false
# finality_depth * block_time / 60 secs = < 1 min (finality time)
NoNewFinalizedHeadsThreshold = '1m'

[GasEstimator]
EIP1559DynamicFees = false
Mode = 'FeeHistory'

[GasEstimator.FeeHistory]
# block_time was: 1s, per recommendation skip 1-2 blocks
CacheTimeout = '2s'

[GasEstimator.BlockHistory]
BlockHistorySize = 100

[NodePool]
NewHeadsPollInterval = '2s' 
