ChainID = '80002'
FinalityDepth = 500
LogPollInterval = '1s'
MinIncomingConfirmations = 5
NoNewHeadsThreshold = '30s'
RPCBlockQueryDelay = 10
RPCDefaultBatchSize = 100
NoNewFinalizedHeadsThreshold = '12m'

[Transactions]
MaxQueued = 5000

[GasEstimator]
PriceDefault = '25 gwei'
PriceMax = '115792089237316195423570985008687907853269984665.640564039457584007913129639935 tether'
PriceMin = '25 gwei'
EIP1559DynamicFees = true
BumpMin = '20 gwei'
BumpThreshold = 5

[GasEstimator.BlockHistory]
BlockHistorySize = 24

[HeadTracker]
HistoryDepth = 2000
# FinalityDepth > 1k => FinalityTagBypass = false
# https://chainlink-core.slack.com/archives/C07RA1B58CC/p1730983397689179?thread_ts=1730908333.814809&cid=C07RA1B58CC
FinalityTagBypass = false

[NodePool]
SyncThreshold = 10
