# RSK prices its txes in sats not wei
ChainID = '30'
FinalityDepth = 50
LinkContractAddress = '0x14AdaE34beF7ca957Ce2dDe5ADD97ea050123827'
LogPollInterval = '30s'
MinContractPayment = '0.001 link'

[GasEstimator]
# It's about 100 times more expensive than Wei, very roughly speaking
PriceDefault = '50 mwei'
PriceMax = '50 gwei'
PriceMin = '0'
# rsk does not yet support EIP-1559 but this allows validation to pass
FeeCapDefault = '100 mwei'

[HeadTracker]
# FinalityDepth > 1k => FinalityTagBypass = false
# https://chainlink-core.slack.com/archives/C07RA1B58CC/p1730983397689179?thread_ts=1730908333.814809&cid=C07RA1B58CC
FinalityTagBypass = false
