ChainID = '31'
FinalityDepth = 50
LinkContractAddress = '0x8bBbd80981FE76d44854D8DF305e8985c19f0e78'
MinContractPayment = '0.001 link'
LogPollInterval = '30s'

[GasEstimator]
PriceDefault = '50 mwei'
PriceMax = '50 gwei'
PriceMin = '0'
FeeCapDefault = '100 mwei'

[HeadTracker]
# FinalityDepth > 1k => FinalityTagBypass = false
# https://chainlink-core.slack.com/archives/C07RA1B58CC/p1730983397689179?thread_ts=1730908333.814809&cid=C07RA1B58CC
FinalityTagBypass = false
