ChainID = '534352'
FinalityDepth = 10
FinalityTagEnabled = true
ChainType = 'scroll'
LogPollInterval = '5s'
MinIncomingConfirmations = 1
# Scroll only emits blocks when a new tx is received, so this method of liveness detection is not useful
NoNewHeadsThreshold = '0'

[GasEstimator]
EIP1559DynamicFees = true
PriceMin = '1 wei'
BumpMin = '1 gwei'

[GasEstimator.BlockHistory]
BlockHistorySize = 24

[GasEstimator.DAOracle]
OracleType = 'opstack'
OracleAddress = '0x5300000000000000000000000000000000000002'

[HeadTracker]
HistoryDepth = 50
# FinalityDepth > 1k => FinalityTagBypass = false
# https://chainlink-core.slack.com/archives/C07RA1B58CC/p1730983397689179?thread_ts=1730908333.814809&cid=C07RA1B58CC
FinalityTagBypass = false

[OCR]
ContractConfirmations = 1
