ChainID = '280'
ChainType = 'zksync'
FinalityDepth = 10
LogPollInterval = '5s'
MinIncomingConfirmations = 1
NoNewHeadsThreshold = '1m'

[GasEstimator]
LimitDefault = 100_000_000
PriceMax = 18446744073709551615
PriceMin = 0

[GasEstimator.DAOracle]
OracleType = 'zksync'

[HeadTracker]
HistoryDepth = 50
# FinalityDepth > 1k => FinalityTagBypass = false
# https://chainlink-core.slack.com/archives/C07RA1B58CC/p1730983397689179?thread_ts=1730908333.814809&cid=C07RA1B58CC
FinalityTagBypass = false
