[blockchain_a]
chain_id = "31337"
image = "f4hrenh9it/foundry:latest"
port = "8545"
type = "anvil"

[data_provider]
port = 9111

[nodeset]
nodes = 5
override_mode = "each"

[[nodeset.node_specs]]

[nodeset.node_specs.db]
image = "postgres:15.6"
pull_image = true

[nodeset.node_specs.node]
docker_file = "../../plugins/chainlink.Dockerfile"
docker_ctx = "../.."
docker_image_name = "chainlink"
pull_image = true
capabilities = ["./streams"]
user_config_overrides = """"""

[[nodeset.node_specs]]

[nodeset.node_specs.db]
image = "postgres:15.6"
pull_image = true

[nodeset.node_specs.node]
docker_file = "../../plugins/chainlink.Dockerfile"
docker_ctx = "../.."
docker_image_name = "chainlink"
pull_image = true
capabilities = ["./streams"]
user_config_overrides = """"""

[[nodeset.node_specs]]

[nodeset.node_specs.db]
image = "postgres:15.6"
pull_image = true

[nodeset.node_specs.node]
docker_file = "../../plugins/chainlink.Dockerfile"
docker_ctx = "../.."
docker_image_name = "chainlink"
pull_image = true
capabilities = ["./streams"]
user_config_overrides = """"""

[[nodeset.node_specs]]

[nodeset.node_specs.db]
image = "postgres:15.6"
pull_image = true

[nodeset.node_specs.node]
docker_file = "../../plugins/chainlink.Dockerfile"
docker_ctx = "../.."
docker_image_name = "chainlink"
pull_image = true
capabilities = ["./streams"]
user_config_overrides = """"""

[[nodeset.node_specs]]

[nodeset.node_specs.db]
image = "postgres:15.6"
pull_image = true

[nodeset.node_specs.node]
docker_file = "../../plugins/chainlink.Dockerfile"
docker_ctx = "../.."
docker_image_name = "chainlink"
pull_image = true
capabilities = ["./streams"]
user_config_overrides = """"""



