ChainID = '76578'
FinalityDepth = 1
FinalityTagEnabled = false
LinkContractAddress = '0x779877A7B0D9E8603169DdbD7836e478b4624789'
LogPollInterval = '3s'
MinIncomingConfirmations = 1
# Avax subnet only emits blocks when a new tx is received, so this method of liveness detection is not useful.
NoNewHeadsThreshold = '0'
OCR.ContractConfirmations = 1
RPCBlockQueryDelay = 2

[GasEstimator]
Mode = 'BlockHistory'
PriceDefault = '25 gwei'
PriceMax = '115792089237316195423570985008687907853269984665.640564039457584007913129639935 tether'
PriceMin = '25 gwei'

[GasEstimator.BlockHistory]
BlockHistorySize = 24

[HeadTracker]
PersistenceEnabled = false
# FinalityDepth > 1k => FinalityTagBypass = false
# https://chainlink-core.slack.com/archives/C07RA1B58CC/p1730983397689179?thread_ts=1730908333.814809&cid=C07RA1B58CC
FinalityTagBypass = false
