ChainID = '42220'
ChainType = 'celo'
FinalityDepth = 10
LogPollInterval = '5s'
MinIncomingConfirmations = 1
NoNewHeadsThreshold = '1m'
OCR.ContractConfirmations = 1
NoNewFinalizedHeadsThreshold = '1m'

[GasEstimator]
PriceDefault = '5 gwei'
PriceMax = '500 gwei'
PriceMin = '5 gwei'
BumpMin = '2 gwei'

[GasEstimator.BlockHistory]
BlockHistorySize = 12

[HeadTracker]
HistoryDepth = 50
PersistenceEnabled = false
# FinalityDepth > 1k => FinalityTagBypass = false
# https://chainlink-core.slack.com/archives/C07RA1B58CC/p1730983397689179?thread_ts=1730908333.814809&cid=C07RA1B58CC
FinalityTagBypass = false
