ChainID = '37111'
ChainType = 'zksync'
# finality depth for this chain is very inconsistent due to low network traffic. in testing blocks every ~1-2minutes were seen
FinalityDepth = 40
# block rate is dynamic, have seen block times as low as 1s
LogPollInterval = '5s'
# sufficient time for RPC to be labelled out of sync, since blockRate is pretty fast
NoNewHeadsThreshold = '10m'

[GasEstimator] 
EIP1559DynamicFees = false
# limit default set for zk based chains
LimitDefault = 2_500_000_000
# value given by ds&a
FeeCapDefault = '2000 gwei'
# estimators typically estimated < 100gwei but in testing setting below this threshold set off a slew of stale reports and errors
# this value is subject to change prior to QA testing
PriceDefault = '70 gwei'
PriceMax = '2000 gwei'
PriceMin = '70 gwei'
# bump gas aggressively to avoid high amounts of transmit errors
BumpThreshold = 1
BumpPercent = 40

[Transactions]
ResendAfterThreshold = '7m0s'

[GasEstimator.DAOracle]
OracleType = 'zksync'

[HeadTracker]
# l1 batching is done every 8hrs with low network activity setting this value to a rough calculation of ~1tx / 2min * 8hrs
HistoryDepth = 250