ChainID = '59141'
FinalityDepth = 200
NoNewHeadsThreshold = '0'

[GasEstimator]
EIP1559DynamicFees = true
PriceMin = '1 wei'

[Transactions]
ResendAfterThreshold = '3m'

[HeadTracker]
HistoryDepth = 1000
# FinalityDepth > 1k => FinalityTagBypass = false
# https://chainlink-core.slack.com/archives/C07RA1B58CC/p1730983397689179?thread_ts=1730908333.814809&cid=C07RA1B58CC
FinalityTagBypass = false
