ChainID = '1337'
FinalityDepth = 1
MinIncomingConfirmations = 1
MinContractPayment = '100'
NoNewHeadsThreshold = '0s'

[Transactions]
ReaperThreshold = '0s'
ResendAfterThreshold = '0s'

[GasEstimator]
Mode = 'FixedPrice'
PriceMin = '0'
BumpThreshold = 0
FeeCapDefault = '100 micro'
PriceMax = '100 micro'

[HeadTracker]
HistoryDepth = 10
MaxBufferSize = 100
SamplingInterval = '0s'
PersistenceEnabled = false
# FinalityDepth > 1k => FinalityTagBypass = false
# https://chainlink-core.slack.com/archives/C07RA1B58CC/p1730983397689179?thread_ts=1730908333.814809&cid=C07RA1B58CC
FinalityTagBypass = false

[OCR]
ContractConfirmations = 1
