ChainID = '61166'
ChainType = 'zksync'
LogPollInterval = '10s'
NoNewHeadsThreshold = '5m' #blocks production can sometimes be delayed by ~5min
FinalityTagEnabled = true  #based on finality committee decision
FinalityDepth = 40

[GasEstimator]
EIP1559DynamicFees = false
# high LimitDefault for worst case pubdata bytes with BatchGasLimit reduced to 4M in OCR2Config  
LimitDefault = 600_000_000
FeeCapDefault = '2000 gwei'
PriceDefault = '25 mwei'
PriceMax = '2000 gwei'
PriceMin = '25 mwei'

[GasEstimator.BlockHistory]
# increasing this to smooth out gas estimation
BlockHistorySize = 200

[GasEstimator.DAOracle]
OracleType = 'zksync'

[HeadTracker]
HistoryDepth = 250
